spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labdb
    username: labuser
    password: labpass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# folosim schema.sql pentru crearea tabelelor
spring.sql.init.mode: always
spring.sql.init.schema-locations: classpath:schema.sql